apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envVars }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}